### PR TITLE
Prevent too many wildlife and predators

### LINKED ISSUE #70: Too many animals spawns, incorrect behaviour of arrassivity
My friend and I are seeing way too many predators in the game, which is making it too tedious to play. For instance, while walking from the big house in Milton to the gas station, we counted nine wolves. Then, when we went to the cabin in Mystery Lake, there were three black bears within 100 yards of us. This is in game version 2.01-2.02, mod version 12.0, running on Steam, with no mods, voyageur difficulty, and me as the host.

The wolves behave abnormally too. During that walk I was attacked by a wolf twice. The first wolf came at me even though I had a lit torch in my hand. The second wolf attacked me while I was standing right next to a well lit fire I had started. Also, none of the wolves went for any piece of decoy rabbit meat that I dropped.

We became frustrated and quit. But before ending, I decided to host a new game in pilgrim difficulty. The wolves ran away as they should, but as you can see in the screenshot below, there are still way too many of them. There are six in view, one off screen close to my right, and two more off screen to the left, over by the church. Making a total of nine. This was our biggest issue when we played back in March, but I was hoping it would be fixed by now.
image

### PR DESCRIPTION
**Pull request by ljans**
Fixes #70.
I'm aware the code is awful, but it does the job for now.
At least it's better than not playing the game at all because of too many predators.

### CODE REVIEW

**Comment by Filigrani** [comment]
Looks sloppy. Because it actually spawns animal and deletes it. There functions that can temporarily disable spawner for several days. Like when animal killed it's spawn disabled for some time. Maybe instead of THIS. We could just ask host, if that spawn indeed must be disabled for some time instead of spawning? Because currently how it made it looks silly.

**Comment by Filigrani** [comment]
Here is it: https://github.com/Filigrani/SkyCoop/blob/BeforeTFTFT/Shared.cs#L2095

Actually it MUST BE called on host. So looks like, we can just hook up, 

That one instead: https://github.com/Filigrani/SkyCoop/blob/BeforeTFTFT/Shared.cs#L2104

Every time player request if spawner is banned, it ask host, while host actually execute that one method. So if we, make random chance call over there, we can return FALSE to client, and ban that spawner, so any future request will go by FALSE aswell, until ban time passed. What you think about this? It sounds good @RED1cat

**Comment by Filigrani** [comment]
```cs
        public static bool CheckSpawnRegionBanned(string GUID)
        {
            int CanBeUnbannedIn;
            if (MyMod.BannedSpawnRegions.TryGetValue(GUID, out CanBeUnbannedIn))
            {
                if (MyMod.MinutesFromStartServer > CanBeUnbannedIn)
                {
                    MyMod.BannedSpawnRegions.Remove(GUID);
                    return false;
                } else
                {
                    // We need seed for Random, because THAT method can be called in same tick few times,
                    // that will lead to same result. Because by default random seed generated by system time.
                    int Seed = new Guid().GetHashCode();

                    // We do not use UnityEngine.Random, because Shared.cs is used also on Dedicated server
                    // That DOES NOT HAVE Unitys stuff at all.
                    System.Random RNG = new System.Random(Seed);

                    if(RNG.Next(0, 100) <= 23) // with 23% chance ban this spawner, instead of spawning animal.
                    {
                        BanSpawnRegion(GUID);
                        return false;
                    }
                    
                    return true;
                }
            }
            return false;
        }
```

**Comment by Filigrani** [comment]
Alright, so, That change goes to live version of the release 13.1. So I guess I can close that pull request.
Thanks for contribution. Your idea was good, but implementation is spoppy. So Sadly, instead of merging your pull request, I have to cancle it, because mine implementation is more better for that. But anyway, thanks a lot for idea.

> ```cs
>         public static bool CheckSpawnRegionBanned(string GUID)
>         {
>             int CanBeUnbannedIn;
>             if (MyMod.BannedSpawnRegions.TryGetValue(GUID, out CanBeUnbannedIn))
>             {
>                 if (MyMod.MinutesFromStartServer > CanBeUnbannedIn)
>                 {
>                     MyMod.BannedSpawnRegions.Remove(GUID);
>                     return false;
>                 } else
>                 {
>                     // We need seed for Random, because THAT method can be called in same tick few times,
>                     // that will lead to same result. Because by default random seed generated by system time.
>                     int Seed = new Guid().GetHashCode();
> 
>                     // We do not use UnityEngine.Random, because Shared.cs is used also on Dedicated server
>                     // That DOES NOT HAVE Unitys stuff at all.
>                     System.Random RNG = new System.Random(Seed);
> 
>                     if(RNG.Next(0, 100) <= 23) // with 23% chance ban this spawner, instead of spawning animal.
>                     {
>                         BanSpawnRegion(GUID);
>                         return false;
>                     }
>                     
>                     return true;
>                 }
>             }
>             return false;
>         }
> ```

**Comment by ljans** [comment]
Thank you very much for tackling the problem in a clean way.
SkyCoop is great, keep up the good work!

**Pull request closed without merging**
